modLoader="javafml"
loaderVersion="[4,)"
license="MIT"
logoFile="logo.png"

[[mods]]
modId="tryckysrtp"
version="1.0.0"
displayName="Trycky's RTP"
authors="Trycky"
description='''
Adds /rtp (random teleport) for NeoForge servers.
Includes a per-player cooldown and safe location search.
'''
displayURL="https://github.com/Trycky64/Tryckys-RTP"
issueTrackerURL="https://github.com/Trycky64/Tryckys-RTP/issues"

[[dependencies.tryckysrtp]]
modId="neoforge"
type="required"
versionRange="[21.1.218,)"
ordering="NONE"
side="BOTH"

[[dependencies.tryckysrtp]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"